name: Test Deployment

on:
  workflow_dispatch:

jobs:
  deploy-to-test:
    name: Deploy to Test Environment
    uses: benwk/github-action/.github/workflows/deployment-cloudflare-pages.yml@main
    with:
      environment: test
      public-domain: d3lay.test.delay.dev
      public-twitter: delay_work
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
