name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  vitest-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.labels.*.name, 'enhancement') || contains(github.event.pull_request.labels.*.name, 'bug') || contains(github.event.pull_request.labels.*.name, 'release')
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Vitest run
        run: npx vitest --coverage
      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
      - name: Add Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: unit
